# Programa pra ver comandos
n = input('Digite algo')
print('O tipo Primitivo desse numero é {}'.format(type(n)))
print('So tem espaço? {}'.format(n.isspace()))
print('É um numero? {}'.format(n.isnumeric()))
print('É uma Letra? {}'.format(n.isalpha()))
print('Tem letras e numeros? {}'.format(n.isalnum()))
print('Esta em letras maisculas? {}'.format(n.isupper()))
print('Esta em letras minuscular {}'.format(n.islower()))
print('Esta capitalizada? {}'.format(n.istitle()))